### ISSUE TITLE
Inertia.js v1.0 has been released.

### ISSUE THREAD

**Issue by gtamasmolnar** [tcampbPPU/ts-inertia-vue#1]
Hi Tanner,

Thanks to your blog I was able to use typescript in a laravel jetstream:inertia project for the first time.
I was really happy about that.

If you have a bit of time, please update your blogpost and the repo due to changes in inertia.js.

[upgrade guide](https://inertiajs.com/upgrade-guide)

Thank you

Tamas Molnar

TLDR:
npm remove @inertiajs/inertia @inertiajs/inertia-vue3 @inertiajs/progress @inertiajs/server
npm install @inertiajs/vue3

**Comment by tcampbPPU** [comment]
@gtamasmolnar thats great to hear my post help you out! Yup I can update that both here any updates in my post.

**Comment by tcampbPPU** [comment]
Thanks again for the feedback, I updated both here on & on my blog. One thing regarding the Inertia v1 release (as I put a mention in my blog) is they changed/removed the `PageProps` type. So where I mention about creating a cast like `resources/js/types/inertia.d.ts` there doesn't seem like easy way to do so, since its a `usePage` function now.

So just to clarify something like is no longer valid:
```ts
const user = computed(() => (usePage().props.value as inertia.Props).user)
```
But you should be able to cast it to a type, just probably more like:
```ts
const user = computed(() => usePage().props?.user) as ComputedRef<User>
```

**Comment by gtamasmolnar** [comment]
Thank you. I really appreciate it. I'm pretty sure it helps other developers too.
I did not find any proper docs on this matter before.
